In [4]:
import pandas as pd
data = pd.read_csv('IRIS.csv')
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [6]:
selected_columns=data[['sepal_length','sepal_width']]
print(selected_columns)


     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]


In [7]:
filtered_data = data[data['sepal_length']>5]
print(filtered_data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[118 rows x 5 columns]


In [18]:
grouped_data = data.groupby('species')['sepal_width'].sum()
print(grouped_data)

species
Iris-setosa        170.9
Iris-versicolor    138.5
Iris-virginica     148.7
Name: sepal_width, dtype: float64


In [19]:
data1=pd.read_csv('IRIS.csv')
data2=pd.read_csv('IRIS-COPY1.csv')
print(data1,data2)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]      sepal_length  sepal_width  petal_length  petal_width         species
0             

In [22]:
merged_data=pd.merge(data1,data2,on='species')
print(merged_data)

      sepal_length_x  sepal_width_x  petal_length_x  petal_width_x  \
0                5.1            3.5             1.4            0.2   
1                5.1            3.5             1.4            0.2   
2                5.1            3.5             1.4            0.2   
3                5.1            3.5             1.4            0.2   
4                5.1            3.5             1.4            0.2   
...              ...            ...             ...            ...   
7495             5.9            3.0             5.1            1.8   
7496             5.9            3.0             5.1            1.8   
7497             5.9            3.0             5.1            1.8   
7498             5.9            3.0             5.1            1.8   
7499             5.9            3.0             5.1            1.8   

             species  sepal_length_y  sepal_width_y  petal_length_y  \
0        Iris-setosa             5.1            3.5             1.4   
1        Iris-set

In [25]:
data.fillna(0,inplace=True)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [38]:
def process_value(value):
    # Apply custom logic to process each value
    processed_value = value*2
    return processed_value

data['neww']=data['sepal_length'].apply(process_value)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species  \
0           163.2          3.5           1.4          0.2     Iris-setosa   
1           156.8          3.0           1.4          0.2     Iris-setosa   
2           150.4          3.2           1.3          0.2     Iris-setosa   
3           147.2          3.1           1.5          0.2     Iris-setosa   
4           160.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145         214.4          3.0           5.2          2.3  Iris-virginica   
146         201.6          2.5           5.0          1.9  Iris-virginica   
147         208.0          3.0           5.2          2.0  Iris-virginica   
148         198.4          3.4           5.4          2.3  Iris-virginica   
149         188.8          3.0           5.1          1.8  Iris-virginica   

     processed  processed_value   new   neww  
0         20.4             2

NameError: name 'pivot' is not defined

In [43]:
data = pd.read_csv('IRIS.csv')
print(data)
pivot_table = pd.pivot_table(data,values='sepal_length',index='petal_length',columns='species')
print(pivot_table)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
species       Iris-setosa  Iris-versicolor  Iris-virginica
petal_length                 

In [45]:
data['species']=pd.to_datetime(data['species'])
data.set_index('species',inplace=True)
resampled_data=data.resample('M').sum()
print(resampled_data)

ParserError: Unknown string format: Iris-setosa present at position 0

In [46]:
import numpy as np

# Create a 1-dimensional array
arr=np.array([1,2,3,4,5])

# basic operations
print(arr)
print("Sum :",np.sum(arr))
print("Mean :",np.mean(arr))
print("Max :",np.max(arr))
print("Min :",np.min(arr))





[1 2 3 4 5]
Sum : 15
Mean : 3.0
Max : 5
Min : 1


In [49]:
# Reshape the array to 2*3 matrix
reshaped_arr=arr.reshape(2,3)
print(reshaped_arr)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [50]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [ ]:
import numpy as np

# 2-dimensional array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#compute statistical measures



In [51]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6]])

# Sum along rows(axis=0)
sum_along_rows = np.sum(data,axis=0)

# Sum along columns(axis=1)
sum_along_columns = np.sum(data,axis=1)

print(sum_along_rows)
print(sum_along_columns)




[ 9 12]
[ 3  7 11]


In [54]:
import numpy as np

# Create a 1-dimensional array
data = np.array([1,2,3,4,5])
# Indexing
print(data[1]) #Access element at index 1


# Boolean masking
mask=data>2
filtered_data=data[mask]
print(filtered_data)

2
[3 4 5]


In [57]:
import numpy as np
data=np.array([0,1,1,2,2,3,3,3,4,4,5,5,5,5])

# Unique elements
unique_ele = np.unique(data)

# Count occurrence of unique ele
ele_counts = np.bincount(data)

print(unique_ele)
print(ele_counts)

[0 1 2 3 4 5]
[1 2 2 3 2 4]


In [59]:
#simulated data for linear regression
x=np.array([1,2,3,4,5])
y=np.array([2,4,5,4,5])
#perform linear regression uusing NUMPY'S polyfit
coefficients=np.polyfit(x,y,1)
#extract slope and intercept from the coefficient
slope,intercept=coefficients
print('slope',slope)
print('intercept',intercept)


slope 0.6
intercept 2.2
